name: Example iOS Project Build

# 这是一个示例配置，展示如何在你的项目中使用可复用workflow

on:
  workflow_dispatch:
    inputs:
      upload_to_appstore:
        description: '是否上传到App Store Connect'
        type: choice
        options: ['true', 'false']
        default: 'true'

jobs:
  build:
    uses: ZClee128/uploadAppStore/.github/workflows/reusable-ios-build.yml@main
    with:
      # 修改为你的项目配置
      workspace_name: "YourApp.xcworkspace"
      scheme_name: "YourApp"
      bundle_id: "com.yourcompany.yourapp"
      provisioning_profile_name: "YourApp"
      
      # 可选配置
      configuration: "Release"
      xcode_version: "latest-stable"
      upload_to_appstore: ${{ github.event.inputs.upload_to_appstore == 'true' }}
      obfuscation_script_path: "scripts/advanced_obfuscate.py"
      
    secrets:
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
